### PR TITLE
Issue 4: String Handling

### PR DESCRIPTION
**Pull request by sjernigan**
I think this will take care of it

### CODE REVIEW

**Comment by dfinninger** [comment]
I'll check it out.

**Comment by dfinninger** [comment]
@sjernigan I think you are using an old branch, can you pull in my latest master and update this PR?

**Comment by sjernigan** [comment]
Opps, yes I still had my old branch around.   I'm going to close this PR and open a new one.

**Comment by dfinninger** [comment]
Sounds good!

**Pull request closed without merging**
